// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetEnvInfo():Promise<Record<string, string>>;

export function GetRuleCategories():Promise<Array<string>>;

export function GetRulesPreview():Promise<Array<model.CleanRule>>;

export function GetRulesWarnings():Promise<Array<string>>;

export function Ping():Promise<string>;

export function Scan():Promise<model.ScanResult>;
