// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Clean(arg1:Array<model.ScanItem>,arg2:boolean):Promise<model.CleanResult>;

export function GetEnvInfo():Promise<Record<string, string>>;

export function GetOperationLogs(arg1:number):Promise<Array<model.OperationLog>>;

export function GetRuleCategories():Promise<Array<string>>;

export function GetRulesPreview():Promise<Array<model.CleanRule>>;

export function GetRulesWarnings():Promise<Array<string>>;

export function Ping():Promise<string>;

export function QuarantinePlugins(arg1:Array<model.ScanItem>):Promise<model.QuarantineResult>;

export function Scan():Promise<model.ScanResult>;

export function ListQuarantineRecords():Promise<Array<model.QuarantineRecord>>;

export function RestoreQuarantinedPlugin(arg1:string):Promise<model.QuarantineResult>;
