// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean(arg1, arg2) {
  return window['go']['app']['App']['Clean'](arg1, arg2);
}

export function GetEnvInfo() {
  return window['go']['app']['App']['GetEnvInfo']();
}

export function GetOperationLogs(arg1) {
  return window['go']['app']['App']['GetOperationLogs'](arg1);
}

export function GetRuleCategories() {
  return window['go']['app']['App']['GetRuleCategories']();
}

export function GetRulesPreview() {
  return window['go']['app']['App']['GetRulesPreview']();
}

export function GetRulesWarnings() {
  return window['go']['app']['App']['GetRulesWarnings']();
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function Scan() {
  return window['go']['app']['App']['Scan']();
}
